/*******************************************************************************
PURPOSE:
  (Define the MassPropertiesDispersions class, a class that is primarily
   simple data storage, with the potential to be used for generating
   dispersions using random number generators.)

ASSUMPTIONS:
  (poi values are representative of deltas to the negative integrals;
   the value is simply added in to the inertia tensor.
   E.g. inertia[0][1] += poi[0]
   If the values are uncorrelated random values, the sign is irrelevant, but if
   the poi values are correlated with some other value, such as mass or moi,
   the sign can be significant.)

LIBRARY DEPENDENCIES:
  (../src/mass_properties_dispersions.cc)

PROGRAMMERS:
  (((Gary Turner) (OSR) (August 2015) (Antares) (Initial version))
   ((Brent Caughron) (OSR) (July 2017) (Antares) (IV&V model code cleanup))
   ((Gary Turner) (OSR) (April 2018) (Antares) (Refactor))
   ((Brent Caughron) (OSR) (Mar 2021) (Antares) (Secondary IV&V)))
*******************************************************************************/

#ifndef CML_MASS_PROPERTIES_DISPERSIONS_HH
#define CML_MASS_PROPERTIES_DISPERSIONS_HH

/*******************************************************************************
MassPropertiesDispersions
PURPOSE: (Primarily data-storage. May include some dispersion functionality
          in later versions of this model.)
*******************************************************************************/
class MassPropertiesDispersions {
public:
  enum DispersionMatch {
  // Allows the setting of 1 value and its application to other values.
  // Always set the lower-indexed value.
    DispMatchNone = 0,
    DispMatchYX   = 10, // y=x
    DispMatchZX   = 20, // z=x
    DispMatchZY   = 21, // z=y
    DispMatchZYX  = 210 // z=y=x
  };


  double mass;         /* (kg)    Dispersed mass. */
  double position[3];  /* (m)     Dispersed position. */
  double moi[3];       /* (kg*m2) Dispersed moments of inertia: xx, yy, zz. */
  double poi[3];       /* (kg*m2) Dispersed products of inertia: xy, xz, yz. */

  DispersionMatch position_match; /* (--) Uses match-options on pos. values. */
  double position_match_sf;       /* (--) The generated value is this multiple
                                          of the originally-dispersed value. */

  DispersionMatch moi_match;      /* (--) Uses match-options on moi values. */
  double moi_match_sf;            /* (--) The generated value is this multiple
                                          of the originally-dispersed value. */

  DispersionMatch poi_match;      /* (--) Uses match-options on poi values. */
  double poi_match_sf;            /* (--) The generated value is this multiple
                                          of the originally-dispersed value. */


  // These variables are optional, but can be used to set the magnitude of
  // the random numbers generated by a Monte-Carlo initialization job.
  // E.G. generate a number between (-mass_disp_mag, +mass_disp_mag); this
  // can then be assigned to mass to be applied as the dispersion.

  double mass_disp_mag;       /* (kg)    Potential mass dispersion. */
  double position_disp_mag[3];/* (m)     Potential position dispersion,
                                         per axis. */
  double moi_disp_mag[3];     /* (kg*m2) Potential disp on moment of inertia. */
  double poi_disp_mag[3];     /* (kg*m2) Potential disp on product of inertia.*/
  unsigned int seed_rand;     /* (--)    Value set in input file to seed the
                                         random number generator. */

  double inertia[3][3];       /* (kg*m2) Dispersed inertia tensor. This is
                                         generated from from moi and poi, it is
                                         not an input array. */

  MassPropertiesDispersions();
  virtual ~MassPropertiesDispersions(){};

  void disp_mag_random_number_generator();
  void generate_inertia_tensor( bool poi_are_negative_integrals);

  void apply_correlations();
  void scale_mass( double nominal);
  void scale_position( double nominal[3]);
  void scale_moi( double nominal_xx,
                  double nominal_yy,
                  double nominal_zz);
  void scale_poi( double nominal_xy,
                  double nominal_xz,
                  double nominal_yz);

private: // and undefined:
  MassPropertiesDispersions (const MassPropertiesDispersions& rhs);
  MassPropertiesDispersions& operator = (const MassPropertiesDispersions& rhs);
};

/*******************************************************************************
MassPropertiesDispersionsFlags
PURPOSE:(POD class containing flags that provide interpretations of values
         set in MassPropertiesDispersions. The intent is that these flags be
         inherited into the class that use MassPropertiesDispersions.)
*******************************************************************************/
class MassPropertiesDispersionsFlags {
public:
  bool random_num_distribution;     /* (--)
    Non monte carlo random number is used. */

  bool mass_disp_is_relative;       /* (--)
    Input data in disperse.mass represents the fraction of the nominal,
    not the actual dispersion. */

  bool pos_disp_is_relative;        /* (--)
    Input data in disperse.position represents the fraction of the nominal,
    not the actual dispersion. */

  bool inertia_moi_disp_is_relative;/* (--)
    Input data in disperse.moi represents the fraction of the nominal,
    not the actual dispersion. */

  bool inertia_poi_disp_is_relative;/* (--)
    Input data in disperse.poi represents the fraction of the nominal,
    not the actual dispersion. */

  bool poi_are_negative_integrals;  /* (--)
    Flag indicating that the poi values are representative of deltas to the
    negative integral -int(x y dm). Default true. */

  MassPropertiesDispersionsFlags();
  virtual ~MassPropertiesDispersionsFlags(){};
private:
  MassPropertiesDispersionsFlags (const MassPropertiesDispersionsFlags& rhs);
  MassPropertiesDispersionsFlags & operator = (
                                  const MassPropertiesDispersionsFlags& rhs);
};
#endif
