exec(open("common_input.py").read())
log_control_flags(5)
log_sub_model_active_flags()
log_relative_velocity()
log_topodetic_ref()
log_topocentric_ref(with_altitude = True)
log_hang_roll_angles()
log_boost_ref()
log_plumbline_ref()
log_range_safety()
log_entry_range()
log_landing_range()
log_launch_range()
log_pt_to_pt()

exec(open("Modified_data/set_points.py").read())
exec(open("Modified_data/set_plumbline_boost_reference.py").read())
exec(open("Modified_data/set_launch_reference.py").read())
exec(open("Modified_data/set_landing_reference.py").read())
exec(open("Modified_data/set_entry_reference.py").read())
exec(open("Modified_data/set_hangroll_body_vectors.py").read())

vehicle.planet_rel_state.subscribe_rel_vel()
vehicle.planet_rel_state.subscribe_topocentric()
vehicle.planet_rel_state.subscribe_topocentric_altitude()
vehicle.planet_rel_state.subscribe_topodetic()
vehicle.planet_rel_state.subscribe_pt_to_pt()
vehicle.planet_rel_state.subscribe_hang_roll()
vehicle.planet_rel_state.subscribe_boost_reference()
vehicle.planet_rel_state.subscribe_plumbline()
vehicle.planet_rel_state.subscribe_range_safety()

vehicle.planet_rel_state.subscribe_entry_range()
vehicle.planet_rel_state.subscribe_landing_range()
vehicle.planet_rel_state.subscribe_launch_range()


# At t=80, unsubscribe everything leaving only the default functionality
trick.add_read(25,"""
vehicle.planet_rel_state.unsubscribe_rel_vel()
vehicle.planet_rel_state.unsubscribe_topocentric()
vehicle.planet_rel_state.unsubscribe_topocentric_altitude()
vehicle.planet_rel_state.unsubscribe_topodetic()
vehicle.planet_rel_state.unsubscribe_pt_to_pt()
vehicle.planet_rel_state.unsubscribe_hang_roll()
vehicle.planet_rel_state.unsubscribe_boost_reference()
vehicle.planet_rel_state.unsubscribe_plumbline()
vehicle.planet_rel_state.unsubscribe_range_safety()
vehicle.planet_rel_state.unsubscribe_entry_range()
vehicle.planet_rel_state.unsubscribe_landing_range()
vehicle.planet_rel_state.unsubscribe_launch_range()
""")

# at t=90, unsubscribe the main model.
trick.add_read(35,"""
vehicle.planet_rel_state.unsubscribe()
""")
trick.stop(40)
