#!/usr/bin/perl

# Purpose: Convert the raw data (text) file into a set of coefficients to
#          be compiled and assigned at model construction time.

# Usage: 
# >> perl convert_raw_data.pl <filename>

$infile = "gggrx_0900c_sha.tab";
open FID , "<$infile" or die;
@data = <FID>;
close FID;

$outfile = "src/GRGM900C_lunar_gravity.cc";
open FID , ">$outfile" or die;

print "Read ",$#data+1," lines\n";

$first_line_num = -1;
# wind through any preamble:
for ($line_num = 0 ; $line_num <= $#data ; $line_num++ ) {
  if ($data[$line_num] =~ /\s*2\s*,\s*0\s*,/) {
    $first_line_num = $line_num;
    print $data[$first_line_num];
    last;
  }
}
if ($first_line_num == -1) {
  print "First data line not found.  Looking for degree 2, order 0.\n";
  die;
}

# Identify any post-data junk
$last_line_num = $#data+1;
for ($line_num = $#data ; $line_num >= $first_line_num ; $line_num-- ) {
  if ($data[$line_num] =~ /(.*),(.*),(.*),(.*),(.*),(.*)/) {
    $last_line_num = $line_num;
    print $data[$last_line_num];
    print "Last element is $1 by $2 \n";
    @C = [];
    @S = [];
    $C[$1] = 0.0;
    $S[$1] = 0.0;
    last;
  }
}
if ($last_line_num == $#data +1) {
  print "Format not recognized.\n";
  die;
}

#Verify format throughout data
for ($line_num = $first_line_num ; $line_num <= $last_line_num ; $line_num++ ) {
  if ($data[$line_num] !~ /(.*),(.*),(.*),(.*),(.*),(.*)/) {
    print "Format not recognized at line $line_num.\n";
    die;
  }
}

# Verif complete, process the data
$deg = 0;
for ($line_num = $first_line_num ; $line_num <= $last_line_num ; $line_num++ ) {
  $data[$line_num] =~ /\s*(\S*)\s*,\s*(\S*)\s*,\s*(\S*)\s*,\s*(\S*)\s*,(.*),(.*)/;
  $ord = $2;
  $c = $3;
  $s = $4;

  if ($1 == $deg) {
    $C[$deg] = $C[$deg].",\n         ";
    $S[$deg] = $S[$deg].",\n         ";
  }
  else {
    $deg = $1;
    $C[$deg] = "  ";
    $S[$deg] = "  ";
  }
  if ($c !~ /^-.*/) {
    $c = " ".$c;
  }
  $C[$deg] = $C[$deg].$c."    /* ($deg,$ord) */";
  if ($s !~ /^-.*/) {
    $s = " ".$s;
  }
  $S[$deg] = $S[$deg].$s."    /* ($deg,$ord) */";
}
$deg_end = $deg;

$dep1 = $deg_end+1;

#create the code:
print FID "/*******************************************************************************\n
Purpose:
  (Grail GRGM900C Lunar Gravity Field, 
   900x900 fully normalized gravity coefficients retrieved from the NASA
   Planetary Data System (PDS) web page 
   File: $infile
   http://pds-geosciences.wustl.edu/grail/grail-l-lgrs-5-rdr-v1/grail_1001/shadr/
 
References:
  (((Lemoine, F.G., et al.)
    (GRGM900C: A degree 900 lunar gravity model from GRAIL primary and 
     extended mission data)
    (Geophys. Res. Lett., 41, 3382–3389, doi:10.1002/2014GL060027)
    (2014)))

Assumptions and Limitations:
  ((1. Gravity coefficients are fully normalized)
   (2. Gravity coefficients are static; no temporal variation.)
  )

Programmers:
  (((Gary Turner) (OSR) (Oct 2015) (Antares) 
                   (Autogenerated from convert_raw_data.pl)))
*******************************************************************************/

#include <cstring> // memcpy

// JEOD includes
#include \"environment/gravity/include/spherical_harmonics_gravity_body.hh\"
#include \"utils/memory/include/jeod_alloc.hh\"
#include \"utils/named_item/include/named_item.hh\"

// Local includes
#include \"../include/GRGM900C_lunar_gravity.hh\"
\n
// NOTE - allocated memory is assigned to the SphericalHarmonicsGravityBody
//        and is destroyed with the SphericalHarmonicsGravityBody.  This
//        model does not have any assigned memory.

/*****************************************************************************
Constructor
Purpose:(Sets the model)
*****************************************************************************/
GRGM900C_LunarGravity::GRGM900C_LunarGravity(
  SphericalHarmonicsGravityBody & body_in)
  :
  grav_body(body_in)
{
  grav_body.planet_name = NamedItem::construct_name (\"Moon\");
  grav_body.degree = $deg_end;
  grav_body.order = $deg_end;
  grav_body.mu = 4.902799967088640E12; // m^3/s^2
  grav_body.radius = 1.738E6; // m
  grav_body.tide_free = true;
  grav_body.tide_free_delta = 0.0;\n
  grav_body.Cnm = JEOD_ALLOC_PRIM_ARRAY ($dep1, double*);
  grav_body.Snm = JEOD_ALLOC_PRIM_ARRAY ($dep1, double*);\n\n";

for ($deg = 2 ; $deg <= $deg_end ; $deg++) {
  $degp1 = $deg+1;
  print FID "  grav_body.Cnm[".$deg."] = JEOD_ALLOC_PRIM_ARRAY(".$degp1.", double);\n";
  print FID "  double temp_C_".$deg."[".$degp1."] =\n      {$C[$deg]\n      };\n";
  print FID "  memcpy (grav_body.Cnm[$deg], temp_C_$deg, sizeof(temp_C_".$deg."));\n\n";
  print FID "  grav_body.Snm[".$deg."] = JEOD_ALLOC_PRIM_ARRAY(".$degp1.", double);\n";
  print FID "  double temp_S_".$deg."[".$degp1."] =\n      {$S[$deg]\n      };\n";
  print FID "  memcpy (grav_body.Snm[$deg], temp_S_$deg, sizeof(temp_S_".$deg."));\n\n";
}
print FID "}";
close FID;
