exec(open( "RUN_02_complete_calc/input.py").read())

trick.add_read(2.0, """
print('*******************************')
print('Angle-calc subscription count:1')
print(atmos_rel_verif.atmos_rel.get_angles_subscription_count())
print('*******************************')
atmos_rel_verif.atmos_rel.subscribe_angles_calculation()
print('*******************************')
print('Angle-calc subscription count:2')
print(atmos_rel_verif.atmos_rel.get_angles_subscription_count())
print('*******************************')
atmos_rel_verif.atmos_rel.unsubscribe_angles_calculation()
print('*******************************')
print('Angle-calc subscription count:1')
print(atmos_rel_verif.atmos_rel.get_angles_subscription_count())
print('*******************************')
""")
trick.add_read(3.0, "atmos_rel_verif.atmos_rel.unsubscribe_angles_calculation()")
trick.add_read(5.0, """
print('*******************************')
print('Angle-calc subscription count:0')
print(atmos_rel_verif.atmos_rel.get_angles_subscription_count())
print('*******************************')
""")
trick.add_read(6.0, "atmos_rel_verif.atmos_rel.unsubscribe_complete_calculation()")
trick.add_read(8.0, """
print('*******************************')
print('Angle-calc subscription count:0')
print(atmos_rel_verif.atmos_rel.get_angles_subscription_count())
print('*******************************')
""")
trick.add_read(9.0, "atmos_rel_verif.atmos_rel.unsubscribe()")

trick.stop(11)
