exec(open("common_input.py").read())
log_control_flags(5)
log_relative_velocity()
log_topocentric_ref(with_altitude = True)
log_topodetic_ref()
log_hang_roll_angles()
log_boost_ref()
log_plumbline_ref()
log_entry_range()
log_landing_range()
log_launch_range()
log_range_safety()

exec(open("Modified_data/set_plumbline_boost_reference.py").read())
exec(open("Modified_data/set_launch_reference.py").read())
exec(open("Modified_data/set_landing_reference.py").read())
exec(open("Modified_data/set_entry_reference.py").read())
exec(open('Modified_data/set_hangroll_body_vectors.py').read())


turn_submodels_on = trick.new_event("turn_submodels_on")
turn_submodels_on.condition( 0, "trick.exec_get_sim_time() >= 20.0")
turn_submodels_on.condition_any()
turn_submodels_on.set_cycle(1.0)
turn_submodels_on.action( 0, """
vehicle.planet_rel_state.subscribe_rel_vel()
vehicle.planet_rel_state.subscribe_topocentric()
vehicle.planet_rel_state.subscribe_topocentric_altitude()
vehicle.planet_rel_state.subscribe_topodetic()
vehicle.planet_rel_state.subscribe_pt_to_pt()
vehicle.planet_rel_state.subscribe_hang_roll()
vehicle.planet_rel_state.subscribe_boost_reference()
vehicle.planet_rel_state.subscribe_plumbline()
vehicle.planet_rel_state.subscribe_entry_range()
vehicle.planet_rel_state.subscribe_landing_range()
vehicle.planet_rel_state.subscribe_launch_range()
vehicle.planet_rel_state.subscribe_range_safety()
""")
turn_submodels_on.activate()
trick.add_event( turn_submodels_on )
