# This is the main workflow for testing CML. It sets up dependencies, builds
# CML, runs unit tests, builds and runs verification sims, and checks to make
# sure that the committed verification data is reproducible.
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          dnf install -y epel-release
          dnf install -y 'dnf-command(config-manager)'
          dnf config-manager --set-enabled crb
          dnf update -y
          dnf install -y \
            bison clang clang-devel cmake diffutils flex gcc \
            gcc-c++ git java-17-openjdk-devel \
            libxml2-devel llvm-devel llvm-static maven ncurses-devel \
            motif motif-devel perl perl-Digest-MD5 python3-devel \
            swig udunits2 udunits2-devel which zlib-devel \
            gtest-devel gmock-devel libasan liblsan libubsan

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure environment
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> "$GITHUB_ENV"
          echo "CML_HOME=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
          echo "TRICK_HOME=$GITHUB_WORKSPACE/externals/trick" >> "$GITHUB_ENV"
          echo "JEOD_HOME=$GITHUB_WORKSPACE/externals/jeod" >> "$GITHUB_ENV"
          if [[ "${{ github.event_name }}" != "pull_request" || \
                "${{ github.event.pull_request.draft }}" == "false" ]]; then
            echo "RUN_VERIF_SIMS=true" >> "$GITHUB_ENV"
          else
            echo "RUN_VERIF_SIMS=false" >> "$GITHUB_ENV"
          fi
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo "SSL_CERT_FILE=/etc/pki/tls/cert.pem" >> "$GITHUB_ENV"

      - name: Set up Python virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install --upgrade pip
          pip3 install .

      - name: Build Trick
        uses: ./.github/actions/build-trick
        with:
          trick-home: ${{ env.TRICK_HOME }}

      - name: Build JEOD
        uses: ./.github/actions/build-jeod
        with:
          trick-home: ${{ env.TRICK_HOME }}
          jeod-home: ${{ env.JEOD_HOME }}

      - name: Build CML and run unit tests
        run: |
          source .bashrc
          cmake --workflow --preset dev --fresh

      # Test that all models build properly in a Trick environment (i.e not using
      # the CMake build process or Trickification). Purge the sim build afterward
      # to save on runner memory usage.
      - name: Check Trick compatibility
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          cd utility/sims/SIM_test_trick_compatibility
          trick-CP
          make spotless

      # Each model category has its verification sims built, run, and sim outputs
      # compared one at a time. After doing so, artifacts are purged. GitHub Actions
      # have limited memory allocated, so attempting to build/run all sims at once
      # is likely to run out of memory.
      - name: Dynamics model verification sims
        id: dynamics_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/dynamics
          git -C models/dynamics clean -x -d -f

      - name: Environment model verification sims
        id: environment_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/environment
          git -C models/environment clean -x -d -f

      - name: Fhw model verification sims
        id: fhw_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/fhw
          git -C models/fhw clean -x -d -f

      - name: Interactions model verification sims
        id: interactions_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/interactions
          git -C models/interactions clean -x -d -f

      - name: Tools model verification sims
        id: tools_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/tools
          git -C models/tools clean -x -d -f

      - name: Utilities model verification sims
        id: utilities_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/utilities
          git -C models/utilities clean -x -d -f

      - name: Vehicle management model verification sims
        id: vehicle_management_verif_sims
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          source .bashrc
          ./bin/test.py builds runs comparisons -j $(nproc) --quiet -m models/vehicle_management
          git -C models/vehicle_management clean -x -d -f

      - name: Generate coverage report
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        run: |
          source .bashrc
          gcovr -r . --exclude-unreachable-branches --exclude-throw-branches \
            --xml-pretty --exclude ${TRICK_HOME}/ --exclude ${JEOD_HOME}/ \
            --exclude '.*/test/.*' --exclude utility/mocks \
            --filter '^models/.*' -o coverage.xml

      - name: Upload coverage report
        if: ${{ env.RUN_VERIF_SIMS == 'true' }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.xml
          format: cobertura

      - name: Upload logs on failure
        if: >-
          ${{ failure() && env.RUN_VERIF_SIMS == 'true' && (
            steps.dynamics_verif_sims.outcome == 'failure' ||
            steps.environment_verif_sims.outcome == 'failure' ||
            steps.fhw_verif_sims.outcome == 'failure' ||
            steps.interactions_verif_sims.outcome == 'failure' ||
            steps.tools_verif_sims.outcome == 'failure' ||
            steps.utilities_verif_sims.outcome == 'failure' ||
            steps.vehicle_management_verif_sims.outcome == 'failure'
          ) }}
        uses: actions/upload-artifact@v4
        with:
          name: verif-sim-failure-logs
          path: bin/logs/*.txt
          if-no-files-found: warn
          retention-days: 2
