# This is the main workflow for testing CML. It sets up dependencies, builds
# CML, runs unit tests, builds and runs verification sims, and checks to make
# sure that the committed verification data is reproducible.
name: Build and Test CML

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          dnf install -y epel-release
          dnf update -y
          dnf install -y bison clang flex git llvm make maven swig cmake clang-devel \
            gcc gcc-c++ java-11-openjdk-devel libxml2-devel llvm-devel llvm-static \
            ncurses-devel openmotif openmotif-devel perl perl-Digest-MD5 udunits2 \
            udunits2-devel which zlib-devel libX11-devel libXt-devel \
            python3-devel diffutils
          dnf config-manager --enable powertools
          dnf install -y gtest-devel gmock-devel

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure environment
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> "$GITHUB_ENV"
          echo "CML_HOME=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
          echo "TRICK_HOME=$GITHUB_WORKSPACE/externals/trick" >> "$GITHUB_ENV"
          echo "JEOD_HOME=$GITHUB_WORKSPACE/externals/jeod" >> "$GITHUB_ENV"

      - name: Set up Python virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build Trick
        uses: ./.github/actions/build-trick
        with:
          trick-home: ${{ env.TRICK_HOME }}
          trick-version: 25.0.2

      - name: Build JEOD
        uses: ./.github/actions/build-jeod
        with:
          trick-home: ${{ env.TRICK_HOME }}
          jeod-home: ${{ env.JEOD_HOME }}
          jeod-version: jeod_v5.4.0

      - name: Build CML and run unit tests
        run: |
          source .venv/bin/activate
          cmake --workflow --preset dev

      - name: Build verification sims
        id: build_verif_sims
        run: |
          export PATH=${TRICK_HOME}/bin:${PATH}
          export CML_HOME=${GITHUB_WORKSPACE}
          source .venv/bin/activate
          ./bin/test.py builds --quiet

      - name: Run verification sims
        id: run_verif_sims
        run: |
          source .venv/bin/activate
          ./bin/test.py runs --quiet

      - name: Compare verification data
        id: compare_verif_sim_data
        run: |
          source .venv/bin/activate
          ./bin/test.py comparisons --quiet

      - name: Generate coverage report
        run: |
          source .venv/bin/activate
          gcovr -r . --exclude-unreachable-branches --exclude-throw-branches \
            --xml-pretty --exclude '.*/test/.*' -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error

      - name: Upload logs on failure
        if: >-
          ${{ failure() && (
            steps.build_verif_sims.outcome == 'failure' ||
            steps.run_verif_sims.outcome == 'failure' ||
            steps.compare_verif_sim_data.outcome == 'failure'
          ) }}
        uses: actions/upload-artifact@v4
        with:
          name: verif-sim-failure-logs
          path: bin/logs/*.txt
          if-no-files-found: warn
          retention-days: 2
