name: Static Analysis

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-format:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --enable powertools
          dnf update -y
          dnf install -y git python3-devel

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure environment
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Python virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install --upgrade pip
          pip3 install .

      # The basenames of all header files need to be unique because our include
      # guards only contain the all-caps basename, not the full paths to files.
      # We don't check files in verif directories since those aren't user-facing
      # and are only used for individual verification sims.
      - name: Header file basenames are unique
        run: |
          violations="$(
              git ls-files 'models/*.hh' 'models/*.h' 'utility/*.hh' 'utility/*.h' ':!*verif*' \
              | awk -F/ '{print $NF}' \
              | tr '[:upper:]' '[:lower:]' \
              | sort \
              | uniq -d
          )"
          if [ -n "$violations" ]; then
            printf 'The following header files do not have unique, case-insensitive names:\n%s\n' "$violations" | tee header-file-name-issues.log
            exit 1
          fi

      - name: Include guards use correct format
        run: |
          source .venv/bin/activate
          violations="$(checkguard -r -p "path 0 | upper | prepend CML_ " models utility)"
          if [ -n "$violations" ]; then
            printf 'Invalid include guards for:\n%s\n' "$violations" | tee include-guard-issues.log
            exit 1
          fi

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: code-format-issues
          path: "*.log"
          if-no-files-found: warn
          retention-days: 2


  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --enable powertools
          dnf update -y
          dnf install -y git make cmake gcc gcc-c++ libxml2-devel openmotif-devel \
            perl perl-Digest-MD5 udunits2-devel zlib-devel libX11-devel libXt-devel \
            python3-devel cppcheck

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure environment
        run: |
          echo "CML_HOME=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
          echo "TRICK_HOME=$GITHUB_WORKSPACE/externals/trick" >> "$GITHUB_ENV"
          echo "JEOD_HOME=$GITHUB_WORKSPACE/externals/jeod" >> "$GITHUB_ENV"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo "SSL_CERT_FILE=/etc/pki/tls/cert.pem" >> "$GITHUB_ENV"

      - name: Clone Trick and JEOD
        run: |
          git clone --depth 1 https://github.com/nasa/trick.git --branch 25.1.0 ${{ env.TRICK_HOME }}
          git clone --depth 1 https://github.com/nasa/jeod.git --branch jeod_v5.4.1 ${{ env.JEOD_HOME }}

      - name: Generate compile commands
        run: cmake --preset user-debug

      # We're suppressing missing includes here. We build with Trick and JEOD set
      # as system include paths, which cppcheck deliberately does not attempt to
      # process. If there's truly a bad include path somewhere, the build itself
      # will fail in a different Action.
      - name: Cppcheck configuration check
        run: |
          cppcheck \
            --project=build/debug/compile_commands.json \
            --check-config \
            --error-exitcode=1 \
            -j $(nproc) \
            --suppress=missingInclude \
            --suppress=unmatchedSuppression \
            2> cppcheck-config.log

      # Note that we're ignoring a few large files which mostly just define data.
      # Cppcheck is absolutely horrible about processing files like those. Luckily,
      # clang-tidy is much faster.
      # We're also suppressing unused function checks because we're building a
      # library; we fully expect some functions to not be called by the rest of the
      # codebase.
      - name: Run Cppcheck
        run: |
          cppcheck \
            --project=build/debug/compile_commands.json \
            --max-configs=1 \
            --enable=all \
            -i ${{ env.CML_HOME }}/models/environment/EGM2008/src/egm_2008_data.cc \
            -i ${{ env.CML_HOME }}/models/environment/gravity/lunar_GRGM900C/data/src/GRGM900C_lunar_gravity.cc \
            -j $(nproc) \
            --suppress=unusedFunction \
            --suppress=unmatchedSuppression \
            --error-exitcode=1 \
            2> cppcheck-check.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-failure-logs
          path: cppcheck-*.log
          if-no-files-found: warn
          retention-days: 2


  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --enable powertools
          dnf update -y
          dnf install -y git make cmake gcc gcc-c++ libxml2-devel openmotif-devel \
            perl perl-Digest-MD5 udunits2-devel zlib-devel libX11-devel libXt-devel \
            python3-devel clang-tools-extra

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure environment
        run: |
          echo "CML_HOME=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
          echo "TRICK_HOME=$GITHUB_WORKSPACE/externals/trick" >> "$GITHUB_ENV"
          echo "JEOD_HOME=$GITHUB_WORKSPACE/externals/jeod" >> "$GITHUB_ENV"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo "SSL_CERT_FILE=/etc/pki/tls/cert.pem" >> "$GITHUB_ENV"

      - name: Clone Trick
        uses: ./.github/actions/build-trick
        with:
          trick-home: ${{ env.TRICK_HOME }}
          clone-only: "true"

      - name: Clone JEOD
        uses: ./.github/actions/build-jeod
        with:
          trick-home: ${{ env.TRICK_HOME }}
          jeod-home: ${{ env.JEOD_HOME }}
          clone-only: "true"

      - name: Generate compile commands
        run: cmake --preset user-debug --fresh

      - name: Run clang-tidy
        run: |
          set -o pipefail
          run-clang-tidy \
            -p build/debug \
            -j $(nproc) \
            -quiet \
            -extra-arg=-Wno-unknown-warning-option \
            -extra-arg=-w \
            | tee clang-tidy.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-failure-logs
          path: clang-tidy.log
          if-no-files-found: warn
          retention-days: 2
